version: "3"

includes:
  model: 
    taskfile: ./taskfile_model.yml

  testing: 
    taskfile: ./taskfile_testing.yml

tasks:
  default:
    desc: Shows all tasks available
    silent: true
    cmds:
      - task -a
